const function_name = ["reverse-text","count-characters","count-word",
"extract-capital-words","extract-lowercase-words","uppercase-text","lowercase-text",
"remove-punctuation","remove-numbers","extract-numbers","remove-stopwords","replace-words","count-word-occurrences",
"find-longest-word","find-shortest-word","remove-duplicate-words","reverse-words-in-sentence",
"remove-whitespace","remove-html-tags","extract-hashtags",
"extract-mentions","extract-emojis","replace-emojis-with-text","remove-emojis",
"remove-non-alphanumeric","extract-acronyms","count-sentences","extract-sentences",
"extract-keywords","find-common-words","find-rare-words","title-case",
"capitalize-words","remove-extra-spaces","extract-dates","extract-times","extract-addresses",
"remove-words-by-length","word-frequencies","remove-brand-names","remove-profanity",
"extract-anagrams","extract-palindromes","remove-specific-words","extract-gendered-words","extract-word-roots",
"word-length-distribution","extract-bigrams","extract-trigrams","extract-quantifiers",
"extract-numbers-with-units","extract-plurals","extract-singulars","remove-singulars",
"extract-ordinal-numbers","extract-cardinal-numbers","extract-roman-numerals",
"extract-currency-symbols","extract-math-symbols","remove-math-symbols","extract-measurement-units",
"remove-measurement-units","extract-sentence-structurem","remove-html-entities","extract-urls",
"remove-urls","extract-email-addresses","remove-email-addresses","extract-phone-numbers","remove-phone-numbers","remove-hashtags",
"remove-mentions","remove-non-english-text","remove-duplicates","remove-blanks",
"normalize-whitespace","extract-text-from-pdf"
];
const description = [
"Reverse Text: Reverses the order of characters in a text.",
"Count Characters: Counts the total number of characters in the text.",
"Count Words: Counts the total number of words in the text.",
"Words Starting with Capital Letter: Retrieves words that begin with a capital letter.",
"Extract Words Starting with Lowercase Letter: Retrieves words that begin with a lowercase letter.",
"Convert Text to Uppercase: Converts all text to uppercase.",
"Convert Text to Lowercase: Converts all text to lowercase.",
"Remove Punctuation: Removes all punctuation marks from the text.",
"Remove Numbers: Removes all numeric digits from the text.",
"Extract Numbers: Retrieves all numeric digits from the text.",
"Remove Stopwords: Removes common stopwords (e.g., 'the', 'is', 'and') from the text.",
"Replace Words: Replaces specified words with alternative words.",
"Count Occurrences of a Word: Counts how many times a specific word occurs in the text." ,
"Find Longest Word: Retrieves the longest word in the text.",
"Find Shortest Word: Retrieves the shortest word in the text.",
"Remove Duplicate Words: Eliminates duplicate words from the text.",
"Reverse Words in a Sentence: Reverses the order of words in a sentence.",
"Remove Whitespace: Removes extra whitespace (spaces, tabs, line breaks) from the text.",
"Remove HTML Tags: Removes HTML tags from the text.",
"Extract Hashtags: Extracts hashtags (words preceded by '#') from the text.",
"Extract Mentions: Extracts user mentions (words preceded by '@') from the text.",
"Extract Emojis: Extracts emojis (symbols representing emotions) from the text.",
"Replace Emojis with Text: Replaces emojis with corresponding text descriptions.",
"Remove Emojis: Removes emojis from the text.",
"Remove Non-Alphanumeric Characters: Removes characters that are not letters or numbers.",
"Extract Acronyms: Extracts acronyms (abbreviations formed from initial letters) from the text.",
"Count Sentences: Counts the total number of sentences in the text.",
"Extract Sentences: Extracts individual sentences from the text.",
"Extract Keywords: Extracts important keywords or phrases from the text.",
"Find Most Common Words: Identifies the most frequently occurring words in the text. ",
"Find Least Common Words: Identifies the least frequently occurring words in the text. ",
"Convert Text to Title Case: Converts text to title case (capitalizes the first letter of each word)",
"Capitalize First Letter of Each Word: Capitalizes the first letter of each word in the text",
"Remove Extra Spaces: Removes extra spaces between words in the text.",
"Extract Dates: Extracts dates (e.g., 'January 1, 2024') from the text.",
"Extract Times: Extracts times (e.g., '10:30 AM') from the text.",
"Extract Addresses: Extracts postal addresses from the text.",
"Remove Words with Certain Length: Removes words with a specified length from the text." ,
"Extract Word Frequencies: Counts the frequency of each word in the text.",
"Remove Brand Names: Removes brand names or trademarks from the text.",
"Remove Profanity: Filters out offensive or inappropriate language from the text.",
"Extract Anagrams: Identifies anagrams (words formed by rearranging the letters) from the text.",
"Extract Palindromes: Identifies palindromes (words that read the same forwards and backwards) from the text." ,
"Remove Specific Words: Removes specific words or phrases from the text.",
"Extract Gendered Words: Identifies gendered words (words associated with a specific gender) from the text.",
"Extract Word Roots: Extracts word roots (base forms of words) from the text." ,
"Calculate Word Length Distribution: Calculates the distribution of word lengths in the text. ",
"Extract Word Bigrams: Extracts pairs of consecutive words (bigrams) from the text.",
"Extract Word Trigrams: Extracts triples of consecutive words (trigrams) from the text. ",
"Extract Quantifiers: Extracts quantifiers (words that indicate quantity) from the text.",
"Extract Numbers with Units: Extracts numbers with units (e.g., '10 meters', '5 kilograms') from the text.",
"Extract Plurals: Extracts plural forms of words from the text. ",
"Extract Singulars: Extracts singular forms of words from the text." ,
"Remove Singulars: Removes singular forms of words from the text. ",
"Extract Ordinal Numbers: Extracts ordinal numbers (e.g., 'first', 'second', 'third') from the text. ",
"Extract Cardinal Numbers: Extracts cardinal numbers (e.g., 'one', 'two', 'three') from the text. ",
"Extract Roman Numerals: Extracts Roman numerals (e.g., 'XII', 'IX', 'VIII') from the text.",
"Extract Currency Symbols: Extracts currency symbols (e.g., '$'', '€', '¥') from the text. " ,
"Extract Math Symbols: Extracts mathematical symbols (e.g., "+", "-", "*", "/") from the text. ",
"Remove Math Symbols: Removes mathematical symbols from the text.",
"Extract Units of Measurement: Extracts units of measurement (e.g., 'meters', 'kilograms', 'liters') from the text. ",
"Remove Units of Measurement: Removes units of measurement from the text. ",
"Extract Sentence Structure: Extracts the grammatical structure of sentences from the text.",
"Remove HTML Entities: Removes HTML entities (special characters represented in HTML format) from the text. ",
"Extract URLs: Extracts URLs (web addresses) from the text.",
"Remove URLs: Removes URLs (web addresses) from the text.",
"Extract Email Addresses: Extracts email addresses from the text.", 
"Remove Email Addresses: Removes email addresses from the text.",
"Extract Phone Numbers: Extracts phone numbers from the text.",
"Remove Phone Numbers: Removes phone numbers from the text.",
"Remove Hashtags: Removes hashtags (words preceded by '#') from the text.",
"Remove Mentions: Removes user mentions (words preceded by '@') from the text.",
"Remove Non-English Text: Removes text written in a language other than English from the text.",
"Remove Duplicates: Removes duplicate lines or sentences from the text.",
"Remove Blanks: Removes blank lines or empty spaces from the text.",
"Normalize Whitespace: Normalizes whitespace (replaces multiple spaces with a single space) in the text. " ,
"Extract Text from PDF: Extracts text content from PDF documents.",
]
console.log(function_name.length);
console.log(description.length);
